name: Deploy Glue Job

on:
  workflow_call:
    inputs:
      region:
        required: true
        default: us-east-1
        type: string
      account:
        required: true
        type: string
      account_number:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: AWS Credentials Configure
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.account_number}}:role/${{inputs.environment}}-compare-file-utility-oidc-role
        role-session-name: GitHubActions
        aws-region: ${{ inputs.region }}

    - name: Calculate MD5 hash of the file
      id: hash
      run: md5sum glue_job.py | awk '{ print $1 }' > current_hash.txt

    - name: Retrieve previous hash from S3
      id: retrieve_hash
      run: aws s3 cp s3://awsgluepocc/previous_hash.txt previous_hash.txt || echo "No previous hash file found"

    - name: Compare hashes
      id: compare_hashes
      run: |
          if ! cmp -s current_hash.txt previous_hash.txt; then
            echo "File has changed, uploading..."
            echo "upload=true" >> $GITHUB_ENV
          else
            echo "File has not changed, skipping upload..."
            echo "upload=false" >> $GITHUB_ENV
          fi

    - name: Upload to S3
      if: env.upload == 'true'
      run: aws s3 cp glue_job.py s3://awsgluepocc/glue_job.py
           aws s3 cp current_hash.txt s3://awsgluepocc/previous_hash.txt

    - name: Upload current hash to S3
      if: env.upload == 'true'
      run: aws s3 cp current_hash.txt s3://awsgluepocc/previous_hash.txt


#    - name: Upload to S3
#      run: aws s3 cp glue_job.py s3://awsgluepocc/glue_job.py --debug

