name: Deploy Glue Job

on:
  push:
    branches:
      - branch-101

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Upload to S3
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.account_number}}:role/${{inputs.environment}}-compare-file-utility-oidc-role
        role-session-name: GitHubActions
        aws-region: ${{ inputs.region }}
      run: aws s3 cp glue_job.py s3://awsgluepocc/glue_job.py
